name: PR-Licensing

on:
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  licensing_node:
    name: licensing_node
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - name: Run setup-licensed
        uses: jonabc/setup-licensed@v1
        with:
          version: "3.x"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: jonabc/licensed-ci@v1
        with:
          workflow: branch
          github_token: ${{ secrets.GITHUB_TOKEN }}
